### PR TITLE
Implemented a skin browser

### PR DESCRIPTION
**Pull request by V0ID-Whisperer**
Implemented a skin browser and made it use the steam command instead of the steam executable.

### CODE REVIEW

**Comment by V0ID-Whisperer** [comment]
image

**Comment by PhantomGamers** [comment]
Looks really good, thanks so much! I'll look into it more later.

Why are some of these methods marked as obsolete?

**Comment by PhantomGamers** [comment]
> made it use the steam command instead of the steam executable.

Also was there a specific reason for this change? I'm not inherently against it, but if we have the path to the executable why not just use that? Does just calling `steam` work on every platform? I'm not certain.

**Comment by V0ID-Whisperer** [comment]
> > made it use the steam command instead of the steam executable.
> 
> Also was there a specific reason for this change? I'm not inherently against it, but if we have the path to the executable why not just use that? Does just calling `steam` work on every platform? I'm not certain.

Steam wasn't launching correctly for me, it crashed whenever Steam was launched through SFP. Changing that to the command fixed that.

**Comment by V0ID-Whisperer** [comment]
> Does just calling `steam` work on every platform? I'm not certain.
It should work on every platform as long as it was installed correctly

**Comment by PhantomGamers** [comment]
Just pulled it locally and it works great.

My main concern is this `https://us-central1-bettersteam-87b59.cloudfunctions.net/api_v2/api_v2` api, is this something you spun up yourself? Ideally these contents would also just be hosted on github or somewhere that people can easily submit their own skins to be added.

Also just minor things would be I think the content of the page should have margins on the side so it doesn't start immediately after the navigation pane, and I think there should be a button to switch to the theme directly after you download it rather than having to download it and then go to settings to enable it.

**Comment by V0ID-Whisperer** [comment]
> Just pulled it locally and it works great.
> 
> My main concern is this `https://us-central1-bettersteam-87b59.cloudfunctions.net/api_v2/api_v2` api, is this something you spun up yourself? Ideally these contents would also just be hosted on github or somewhere that people can easily submit their own skins to be added.
> 
> Also just minor things would be I think the content of the page should have margins on the side so it doesn't start immediately after the navigation pane, and I think there should be a button to switch to the theme directly after you download it rather than having to download it and then go to settings to enable it.

Grabbed it from Millennium for testing, change it to smth else. The json part of the skin browser should be easy to change

**Comment by PhantomGamers** [comment]
So I'll need to put a bit of work into spinning up a backend solution for this before I can do a release with it but I'll merge it into its own branch for now

**Comment by V0ID-Whisperer** [comment]
Alright if u will need some help drop me a discord message at ``._._v0id_._.``

**Pull request merged**
